version: '3'
services:
    simple-cloud-config-client:
        build: ./simple-cloud-config-client
        ports:
        - 8080:8080
    simple-cloud-config-server:
        build: ./simple-cloud-config-server
        ports:
        - 8888:8888